

GET http://localhost:3000/products

GET http://localhost:3000/produits

### Create an article
POST http://localhost:3000/produits
Content-Type: application/json
Authorization: 1
// c'est pour créer un produit 

{
    "produitsId": 1,
    "name": "NeuroNet",
    "description": "NeuroNet est un jeu de gestion urbaine narratif où vous devez maintenir l'équilibre entre les besoins et les désirs de ses nombreux citoyens, afin de déterminer la destinée d'une ville post-cyberpunk à l'orée d'une nouvelle ère numérique.",
    "categories": ["1","3"],
    "nomPlateforme" : "PC",
    "commentairesId" : ["1","2","3"],
    "taille": "12.4G",
    "image": "backend/images/neuronet.png",
    "priceConseille": "16.78€"
}
/*{
    "produitsId": 2,
    "name": "Game Awards 2021",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 3,
    "name": "The Unliving",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 4,
    "name": "Chants of Sennaar",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 5,
    "name": "Asobu Indie Showcase",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 6,
    "name": "Indiemag",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 7,
    "name": "Street of Rage 4",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 8,
    "name": "Kill It With Fire 2",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 9,
    "name": "Outpost Infinity Siege",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 10,
    "name": "Anger Foot",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 11,
    "name": "Ripout",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 12,
    "name": "Killer Frequency",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 13,
    "name": "Orrstead",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 14,
    "name": "Silicon City",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 15,
    "name": "Tinytopia",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 16,
    "name": "Dwarfheim",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 17,
    "name": "Unleaving",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 18,
    "name": "A Void Hope",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 19,
    "name": "Murders On The Yangtze River",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}
{
    "produitsId": 20,
    "name": "Hauma",
    "description": "",
    "categories": "",
    "nomPlateforme" : "PC",
    "commentairesId" : "",
    "taille": "12.4G",
    "image": "",
    "priceConseille": "17.99€"
}*/


### Update an article
PUT http://localhost:3000/produits/1
Content-Type: application/json

{
    "title": "Produit 3"
}

### Delete an article
DELETE http://localhost:3000/produits/4

-----

### Register
POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "user3",
    "password": "password1"
}

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user2",
    "password": "password1"

}